import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import '../globals.css'
import { Providers } from '../providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Fashion Commerce Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={geistSans.className}>
      <body className="flex">
        <main className="h-screen  w-full flex items-center justify-center pt-5 flex-5 scrollbar-hide bg-black  overflow-y-scroll">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
