import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { AppSidebar } from './_components/nav/Navigation'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'

import './globals.css'
import { Providers } from './providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Fashion Commerce Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <SidebarProvider>
          <AppSidebar />
          <main className="h-screen pt-5 flex-5 scrollbar-hide bg-gray-100  overflow-y-scroll">
            <SidebarTrigger />
            <Providers>{children}</Providers>
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
